installer: Rework the installer
- Switch to new git repo, hosted at https://joshuado.es/git/hangover
- Add support for selecting download mirror, current choices are joshuado.es and GitHub
- Migrate prefix from .winehangover to .hangover
- Sync helpers between installer and launcher
- Rewrite info printout to support git or direct details and last changelog, only if the cache directory exists
- Tell user when migrations take place for a new update
- Print updating instead of downloading when running a git pull
- Add a warning about where to manually install Termux-X11 from if Android refuses to install it

diff --git a/hangover-installer b/hangover-installer
--- a/hangover-installer
+++ b/hangover-installer
@@ -1,11 +1,9 @@
 #!/data/data/com.termux/files/usr/bin/bash
 
-HOSTER=JoshuaDoes
-REPO="https://github.com/JoshuaDoes/winehangover-image"
-BRANCH=dev
-VER="v1.11.0"
+export MAINTAINER=JoshuaDoes
+export VER="v1.11.1"
 
-export WINEPREFIX="$HOME/.winehangover"
+export WINEPREFIX="$HOME/.hangover"
 export CACHE="$WINEPREFIX/.cache"
 export WINEPATH="$WINEPREFIX/wine"
 export WINEBIN="$WINEPATH/arm64-v8a/bin"
@@ -24,6 +22,14 @@ export T="$MNT/t:"
 export Z="$MNT/z:"
 
 export WINEARCH=win64
+export WINEDEBUG=-all
+
+export WINEDLLOVERRIDES="d3d8,d3d9,d3d10core,d3d11,dxgi=n,b"
+if [ ! -f $C/windows/system32/d3d8.dll ]; then
+  WINEDLLOVERRIDES="d3d9,d3d10,d3d10_1,d3d10core,d3d11,dxgi=n,b"
+fi
+
+export DXVK_HUD=version,fps,api,gpuload,devinfo,compiler,scale=0.65
 
 # Hide outputs when unnecessary
 pushd() {
@@ -31,6 +37,12 @@ pushd() {
 }
 popd() {
   command popd "$@" >/dev/null
+}
+wait() {
+  command wait "$@" >/dev/null 2>&1
+}
+disown() {
+  command disown "$@" >/dev/null 2>&1
 }
 mkdir() {
   command mkdir -p "$@" >/dev/null 2>&1
@@ -56,9 +68,6 @@ wget() {
 wget2() {
   command wget "$1" -O "$2" --timestamping --quiet --show-progress
 }
-git() {
-  command git "$@"
-}
 wine() {
   LD_LIBRARY_PATH="$WINEPREFIX/test" \
     command $WINEBIN/wine "$@" >/dev/null 2>&1
@@ -71,6 +80,15 @@ wineserver() {
   LD_LIBRARY_PATH="$WINEPREFIX/test" \
     command $WINEBIN/wineserver "$@" >/dev/null 2>&1
 }
+winedesktop() {
+  wine explorer /desktop=shell,-1x-1 "$cmd" "${args[@]}" >/dev/null 2>&1
+}
+openbox-session() {
+  command openbox-session >/dev/null 2>&1
+}
+xfce4-session() {
+  command xfce4-session >/dev/null 2>&1
+}
 winetricks() {
   LD_LIBRARY_PATH="$WINEPREFIX/test" \
     command $WINEBIN/winetricks "$@" #>/dev/null 2>&1
@@ -78,8 +96,41 @@ winetricks() {
 msiexec() {
   wine msiexec /i "$1" /quiet /qn /norestart
 }
-startx() {
+
+info() {
   echo ""
+  echo "  Termux/Hangover Install & Update"
+  echo "  > $VER"
+  echo ""
+  echo "  Maintainer: $MAINTAINER"
+  case $DL in
+    git)
+      echo "  Hoster:   $HOSTER"
+      echo "  Provider: $PROVIDER"
+      echo "  Repo:     $REPO"
+      echo "  Branch:   $BRANCH"
+      ;;
+    direct)
+      echo "  Hoster:   $HOSTER"
+      echo "  Provider: $PROVIDER"
+      echo "  Source:   $REPO"
+      ;;
+  esac
+
+  if [ -d $CACHE ]; then
+    echo ""
+    echo "Most recent changelog message:"
+    pushd $CACHE
+    if [ -d .git ]; then
+      echo "  $(git log -1 --pretty=format:%B | cat)"
+    elif [ -f LASTCOMMITMSG ]; then
+      echo "  $(cat LASTCOMMITMSG)"
+    fi
+    popd
+  fi
+}
+
+startx() {
   echo "  > Starting an X server"
   termux-x11 -retro $DISPLAY >/dev/null 2>&1 &
   disown
@@ -104,19 +155,41 @@ stopall() {
   stopwine
   killconfirmed
 }
-info() {
-  echo ""
-  echo "  Termux/Hangover Install & Update"
-  echo "    Hosted by $HOSTER"
-  echo "    > $VER"
-  echo "  REPO: $REPO"
-}
+
+### main ###
 
 stopall
 clear
 info
 echo ""
 
+PS3='  Which download mirror should we use? (1-2) '
+menuvar=("JoshuaDoes: CloudFlare" "JoshuaDoes: GitHub" "Exit")
+select menuvar in "${menuvar[@]}"
+do
+  case $menuvar in
+    "JoshuaDoes: CloudFlare")
+      export DL=git
+      export HOSTER=JoshuaDoes
+      export PROVIDER=CloudFlare
+      export REPO="https://joshuado.es/git/hangover"
+      export BRANCH=dev
+      break;;
+    "JoshuaDoes: GitHub")
+      export DL=git
+      export HOSTER=JoshuaDoes
+      export PROVIDER=GitHub
+      export REPO="https://github.com/JoshuaDoes/winehangover-image"
+      export BRANCH=dev
+      break;;
+    "Exit")
+      exit 0
+      break;;
+    *) echo "Invalid option.";;
+  esac
+done
+
+echo ""
 PS3='  Which Vulkan ICD should we use? (1-2) '
 menuvar=("Hangover" "I'll handle my Vulkan" "Exit")
 select menuvar in "${menuvar[@]}"
@@ -138,33 +211,33 @@ do
 done
 
 echo ""
-
-export DXVKDLLS=("d3d8.dll" "d3d9.dll" "d3d10core.dll" "d3d11.dll" "dxgi.dll")
-
 PS3='  Which DXVK release should we use? (1-5) '
 menuvar=("Dyneteve" "Hangover" "Airis" "JoshuaDoes" "Doitsujin" "Exit")
 select menuvar in "${menuvar[@]}"
 do
   case $menuvar in
     "Dyneteve")
+      export DXVKDLLS=("d3d8.dll" "d3d9.dll" "d3d10core.dll" "d3d11.dll" "dxgi.dll")
       export DXVKREL=dyneteve
       export DXVKS=Dyneteve
       break;;
     "Hangover")
+      export DXVKDLLS=("d3d8.dll" "d3d9.dll" "d3d10core.dll" "d3d11.dll" "dxgi.dll")
       export DXVKREL=hangover
       export DXVKS=Hangover
       break;;
     "JoshuaDoes")
+      export DXVKDLLS=("d3d8.dll" "d3d9.dll" "d3d10core.dll" "d3d11.dll" "dxgi.dll")
       export DXVKREL=master
       export DXVKS=JoshuaDoes
       break;;
     "Airis")
-      DXVKDLLS=("d3d9.dll" "d3d10.dll" "d3d10_1.dll" "d3d10core.dll" "d3d11.dll" "dxgi.dll")
+      export DXVKDLLS=("d3d9.dll" "d3d10.dll" "d3d10_1.dll" "d3d10core.dll" "d3d11.dll" "dxgi.dll")
       export DXVKREL=airis
       export DXVKS=Airis
       break;;
     "Doitsujin")
-      DXVKDLLS=("d3d9.dll" "d3d10.dll" "d3d10_1.dll" "d3d10core.dll" "d3d11.dll" "dxgi.dll")
+      export DXVKDLLS=("d3d9.dll" "d3d10.dll" "d3d10_1.dll" "d3d10core.dll" "d3d11.dll" "dxgi.dll")
       export DXVKREL=doitsujin
       export DXVKS=Doitsujin
       break;;
@@ -178,35 +251,65 @@ done
 clear
 info
 
+# Migrations to latest update
 if [ -d $TMPDIR/hangover ]; then
+  echo ""
+  echo "  > Removing legacy download cache"
   rm -rf $TMPDIR/hangover
 fi
-
-echo ""
-echo "  Downloading!"
-pkg install -y git
-if [ ! -d $CACHE/.git ]; then
-  rm -rf $CACHE
-  git clone "$REPO" -b $BRANCH $CACHE
-else
-  pushd $CACHE
-  git pull
-  popd
+if [ ! -d "$WINEPREFIX" ]; then
+  for INST in "$HOME/.winehangover"; do
+    if [ -d "$INST" ]; then
+      echo ""
+      echo "  > Migrating image to:"
+      echo "    $WINEPREFIX"
+      mv "$INST" "$WINEPREFIX"
+      break
+    fi
+  done
 fi
 
 echo ""
-echo "  Most recent changelog message:"
-pushd $CACHE
-echo "    $(git log -1 --pretty=format:%B | cat)"
-popd
+case $DL in
+  git)
+    pkg install -y git
+    if [ ! -d $CACHE/.git ]; then
+      echo "  Downloading image!"
+      echo ""
+      rm -rf $CACHE
+      git clone "$REPO" -b $BRANCH $CACHE
+    else
+      echo "  Updating image!"
+      echo ""
+      pushd $CACHE
+      git remote set-url origin "$REPO"
+      git fetch --all
+      git pull
+      git checkout $BRANCH
+      popd
+    fi
+
+    echo "  Most recent changelog message:"
+    pushd $CACHE
+    echo "    $(git log -1 --pretty=format:%B | cat)"
+    popd
+    ;;
+  direct)
+    echo "  * Direct not yet implemented!"
+    echo ""
+    exit 1
+    ;;
+  *)
+    echo "  * Download type $DL is not supported!"
+    echo ""
+    exit 1
+esac
 
 mkdir $WINEPREFIX
 pushd $WINEPREFIX
 
 echo ""
 echo "  Patching Hangover image unconditionally..."
-echo "  > Installing Termux:X11"
-termux-open $CACHE/apk/termux11.apk
 echo "  > Installing packages"
 pkg install -y x11-repo
 pkg install -y termux-x11-nightly pulseaudio \
@@ -224,7 +327,12 @@ case $PLAT in
     ;;
   *) echo "  > Skipping ICD";;
 esac
+echo "  > Installing Termux:X11"
+termux-open $CACHE/apk/termux11.apk
+echo "  ! If this fails, please manually install:"
+echo "    $CACHE/apk/termux11.apk"
 
+echo ""
 startx
 echo ""
 
